import { DataTypes, Model, Optional } from "sequelize"
import { sequelize } from "../database"
import { User } from "./userModel"
import { Tag } from "./tagModel"

// Define the interface for Post attributes
interface PostAttributes {
  id: string
  text: string
  votes: number
  userId: string
}

// Define the interface for creating Post instances
// (allows for optional 'id' and 'votes' during creation)
interface PostCreationAttributes
  extends Optional<PostAttributes, "id" | "votes"> {}

// Define the Post model extending Sequelize's Model class
class Post
  extends Model<PostAttributes, PostCreationAttributes>
  implements PostAttributes
{
  declare id: string
  declare text: string
  declare votes: number
  declare userId: string

  // Association methods (generated by Sequelize)

  declare getUser: () => Promise<User>
  declare getTags: () => Promise<Tag[]> // Get all tags associated with a post
  declare addTag: (tag: Tag) => Promise<void> // Add an existing tag to a post
  declare createTag: (tagDetails: any) => Promise<Tag> // Create a new tag for a post
  declare hasTag: (tag: Tag) => Promise<boolean> // Check if a post has a specific tag
  declare countTags: () => Promise<number> // Count the number of tags for a post
  declare updateTags: (tags: Tag[]) => Promise<void> // Update the tags associated with a post
  declare deleteTags: (tags: Tag[]) => Promise<void> // Delete the tags associated with a post
}

// Initialize the Post model with its attributes and options
Post.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true
    },
    text: {
      type: DataTypes.STRING,
      allowNull: false
    },
    votes: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: 0
    },
    userId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: {
        model: User,
        key: "id"
      }
    }
  },
  {
    sequelize,
    modelName: "post"
  }
)

export { Post, PostAttributes }
